# Generated by Django 5.0 on 2025-11-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='face_encoding',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='use_face_auth',
        ),
    ]
